apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: docker.io/shkatara/python-custom-metrics-prometheus:latest
        name: python-custom-metrics-prometheus
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  ports:
  - name: http
    nodePort: 30115
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: test
  type: NodePort
